apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  namespace: db
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 256M
  hostPath:
    path: /db
